<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MATUS-LENOVO" name="com.evolveum.polygon.test.scim.Testclass" tests="8" failures="7" timestamp="8 Aug 2016 14:12:10 GMT" time="3.458" errors="0">
  <testcase name="createObjectOnResourcesTest" time="0.600" classname="com.evolveum.polygon.test.scim.Testclass">
    <failure type="org.identityconnectors.framework.common.exceptions.ConnectorIOException" message="Query for creating new object was unsuccessful. Status code returned: 400">
      <![CDATA[org.identityconnectors.framework.common.exceptions.ConnectorIOException: Query for creating new object was unsuccessful. Status code returned: 400
	at com.evolveum.polygon.scim.ScimCrudManager.onNoSuccess(ScimCrudManager.java:1006)
	at com.evolveum.polygon.scim.ScimCrudManager.createEntity(ScimCrudManager.java:647)
	at com.evolveum.polygon.scim.ScimConnector.create(ScimConnector.java:202)
	at com.evolveum.polygon.test.scim.TestConfiguration.createResourceTestHelper(TestConfiguration.java:283)
	at com.evolveum.polygon.test.scim.Testclass.createObjectOnResourcesTest(Testclass.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- createObjectOnResourcesTest -->
  <testcase name="filterMethodTest" time="0.000" classname="com.evolveum.polygon.test.scim.Testclass"/>
  <testcase name="createObjectOnResourcesTest" time="0.584" classname="com.evolveum.polygon.test.scim.Testclass">
    <failure type="org.identityconnectors.framework.common.exceptions.ConnectorIOException" message="Query for creating new object was unsuccessful. Status code returned: 400">
      <![CDATA[org.identityconnectors.framework.common.exceptions.ConnectorIOException: Query for creating new object was unsuccessful. Status code returned: 400
	at com.evolveum.polygon.scim.ScimCrudManager.onNoSuccess(ScimCrudManager.java:1006)
	at com.evolveum.polygon.scim.ScimCrudManager.createEntity(ScimCrudManager.java:647)
	at com.evolveum.polygon.scim.ScimConnector.create(ScimConnector.java:215)
	at com.evolveum.polygon.test.scim.TestConfiguration.createResourceTestHelper(TestConfiguration.java:285)
	at com.evolveum.polygon.test.scim.Testclass.createObjectOnResourcesTest(Testclass.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- createObjectOnResourcesTest -->
  <testcase name="updateUserResourceObjectTest" time="0.000" classname="com.evolveum.polygon.test.scim.Testclass"/>
  <testcase name="deleteObjectfromResourcesTest" time="0.000" classname="com.evolveum.polygon.test.scim.Testclass"/>
  <testcase name="configurationTest" time="2.274" classname="com.evolveum.polygon.test.scim.Testclass"/>
  <testcase name="updateGroupResourceObjectTest" time="0.000" classname="com.evolveum.polygon.test.scim.Testclass"/>
  <testcase name="listAllfromResourcesTest" time="0.000" classname="com.evolveum.polygon.test.scim.Testclass"/>
</testsuite> <!-- com.evolveum.polygon.test.scim.Testclass -->
